package br.com.reservafacil.agendamento.controller;

import org.junit.Test;

public class AgendamentoTransferenciaBancariaControllerTest {

	@Test
	public void DEVE_EXIBIR_TELA_DE_ERRO_QUANDO_SALDO_FOR_INSUFICIENTE() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_A() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_B_COM_TAXA_DE_10_REAIS() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_B_COM_TAXA_DE_8_REAIS() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_C_COM_TAXA_DE_12_PORCENTO() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_C_COM_TAXA_DE_21_PORCENTO() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_C_COM_TAXA_DE_43_PORCENTO() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_C_COM_TAXA_DE_54_PORCENTO() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_C_COM_TAXA_DE_67_PORCENTO() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_C_COM_TAXA_DE_74_PORCENTO() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_C_COM_TAXA_DE_83_PORCENTO() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_D_COM_VALOR_ATE_25000_REAIS() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_D_COM_VALOR_DE_25001_A_120000_REAIS() {
		
	}
	
	@Test
	public void DEVE_REALIZAR_AGENDAMENTO_COM_TRANSACAO_DE_TIPO_D_COM_VALOR_MAIOR_DE_120000_REAIS() {
		
	}
}
